#!/bin/bash  
#Setting python virtual environment
python3 -m venv pEnvironment-env
source pEnvironment-env/bin/activate
pip3 install numpy
# Getting patchelf
cd patchelf
./configure --prefix="$HOME/.local"
make install
strip --strip-unneeded ~/.local/bin/patchelf
gzip -9 ~/.local/share/man/man1/patchelf.1
## setting NS libraries
lib_absPATH= readlink -f NS_lib
patchelf --set-rpath $lib_absPATH/ NanoShaper
patchelf --set-interpreter $lib_absPATH/ld-linux-x86-64.so.2 NanoShaper
patchelf --add-needed librt.so.1 NanoShaper
patchelf --add-needed libpthread.so.0 NanoShaper
## Getting pdb2pqr
pip3 install pdb2pqr
